### ISSUE TITLE
[BUG] objc_msgSend not working on macOS

### ISSUE THREAD

**Issue by StarOnTheSky** [InfectionDust/teeuniverse#2] opened 2022-02-06 08:16 UTC
Compiler error output:
```
In file included from /Users/tianyi/teeuniverse/src/client/components/graphics_backend_sdl.cpp:34:
/Users/tianyi/teeuniverse/src/client/components/graphics_backend_sdl.h:75:4: error: no matching function for call to 'objc_msgSend'
                        objc_msgSend(m_Pool, selector);
                        ^~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/objc/message.h:63:1: note: candidate function not viable: requires 0 arguments, but 2 were provided
objc_msgSend(void /* id self, SEL op, ... */ )
^
In file included from /Users/tianyi/teeuniverse/src/client/components/graphics_backend_sdl.cpp:34:
/Users/tianyi/teeuniverse/src/client/components/graphics_backend_sdl.h:81:4: error: no matching function for call to 'objc_msgSend'
                        objc_msgSend(m_Pool, selector);
                        ^~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/objc/message.h:63:1: note: candidate function not viable: requires 0 arguments, but 2 were provided
objc_msgSend(void /* id self, SEL op, ... */ )
^
[ 68%] Building CXX object CMakeFiles/teeuniverse_client.dir/src/client/gui/duration-edit.cpp.o
/Users/tianyi/teeuniverse/src/client/components/graphics_backend_sdl.cpp:409:4: warning: 'gluBuild2DMipmaps' is deprecated: first deprecated in macOS 10.9 - "Use glGenerateMipmap" [-Wdeprecated-declarations]
                        gluBuild2DMipmaps(GL_TEXTURE_2D, StoreOglformat, Width, Height, Oglformat, GL_UNSIGNED_BYTE, pTexData);
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:247:14: note: 'gluBuild2DMipmaps' has been explicitly marked deprecated here
extern GLint gluBuild2DMipmaps (GLenum target, GLint internalFormat, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *data) OPENGL_DEPRECATED_MSG(10_0, 10_9, "Use glGenerateMipmap");
             ^
1 warning and 2 errors generated.
make[2]: *** [CMakeFiles/teeuniverse_client.dir/src/client/components/graphics_backend_sdl.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/tianyi/teeuniverse/src/client/components/graphics.cpp:39:
/Users/tianyi/teeuniverse/src/client/components/graphics_backend_sdl.h:75:4: error: no matching function for call to 'objc_msgSend'
                        objc_msgSend(m_Pool, selector);
                        ^~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/objc/message.h:63:1: note: candidate function not viable: requires 0 arguments, but 2 were provided
objc_msgSend(void /* id self, SEL op, ... */ )
^
In file included from /Users/tianyi/teeuniverse/src/client/components/graphics.cpp:39:
/Users/tianyi/teeuniverse/src/client/components/graphics_backend_sdl.h:81:4: error: no matching function for call to 'objc_msgSend'
                        objc_msgSend(m_Pool, selector);
                        ^~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/objc/message.h:63:1: note: candidate function not viable: requires 0 arguments, but 2 were provided
objc_msgSend(void /* id self, SEL op, ... */ )
^
2 errors generated.
make[2]: *** [CMakeFiles/teeuniverse_client.dir/src/client/components/graphics.cpp.o] Error 1
make[1]: *** [CMakeFiles/teeuniverse_client.dir/all] Error 2
make: *** [all] Error 2
```
Complier version: Clang 13 from XCode
OS: macOS Monterey 12.2
According to [Apple's document](https://developer.apple.com/documentation/objectivec/1456712-objc_msgsend), `objc_msgSend` has no arguments. The SDL backend for macOS may have to be updated.

**Comment by StarOnTheSky** [comment] 2022-02-06 08:44
`objc_msgSend` with arguments is only availablle in macOS < 10 :(

**Comment by StarOnTheSky** [comment] 2022-02-06 11:05
Currently removing this function makes it works.

**Comment by Kaffeine** [comment] 2022-02-13 18:07
Hello. Somehow I've missed the issue.

I found this commit: https://github.com/ddnet/ddnet/commit/47b41f35ffdbc991a6f3ccf886bdbda1b6192343 and [applied](https://github.com/InfectionDust/teeuniverse/commit/aa9aa21f2e77de482b22685c26ea89fb5123aa34) it to `teeuniverse`.

Probably the issue is fixes (closing for now), feel free to reopen it in case of a trouble.

Thank you for the bugreport! I have no access to macOS and I didn't expect anyone to try it :smile:. It is nice that you compiled this!

**Closed by Kaffeine** 2022-02-13 18:07 UTC
